name: Capacitor Android Full Project & Artifact v4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm list --depth=0

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli@6.2.1

      - name: Build project (if build script exists)
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script found, skipping build step"
          fi

      - name: Sync Capacitor
        run: |
          npx cap sync
          npx cap update

      - name: Copy web assets to Android
        run: npx cap copy android

      - name: Update Android project
        run: npx cap update android

      - name: Verify Android project structure
        run: |
          echo "📁 Project structure:"
          find android/app/src/main/assets -name "*.html" -o -name "*.js" -o -name "*.css" | head -10
          echo "📱 Capacitor config:"
          cat capacitor.config.json

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Android Debug APK
        run: |
          cd android
          ./gradlew assembleDebug \
            --no-daemon \
            --warning-mode all \
            --stacktrace

      - name: Build Android Release APK (unsigned)
        run: |
          cd android
          ./gradlew assembleRelease \
            --no-daemon \
            --warning-mode all \
            --stacktrace

      - name: List generated APK files
        run: |
          find android/app/build/outputs -name "*.apk" -type f | while read file; do
            echo "📦 Found APK: $file"
            ls -la "$file"
          done

      - name: Upload Android Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Upload Android Release APK (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk-unsigned
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 30

      - name: Upload all APKs (backup)
        uses: actions/upload-artifact@v4
        with:
          name: all-apk-files
          path: android/app/build/outputs/apk/
          retention-days: 7

      - name: Build summary
        run: |
          echo "🎉 Build completed successfully!"
          echo "📱 Generated APKs:"
          find android/app/build/outputs -name "*.apk" -type f | while read file; do
            size=$(ls -lh "$file" | awk '{print $5}')
            echo "   - $(basename "$file") ($size)"
          done
