name: Capacitor Android Full Project & Artifact v4

on:
  push:
    branches:
      - main
 
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clean package locks
        run: |
          rm -rf node_modules package-lock.json

      - name: Install Capacitor CLI globally
        run: npm install -g @capacitor/cli@latest

      - name: Install dependencies (including filesystem)
        run: npm install

      - name: Install Capacitor Filesystem
        run: npm install @capacitor/filesystem

      - name: Sync Capacitor
        run: npx cap sync

      - name: Copy web to Android
        run: npx cap copy android

      - name: Set Java version for Android
        run: |
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "Using Java version:"
          java -version

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Android Debug APK
        run: cd android && ./gradlew assembleDebug --no-daemon --warning-mode all

      - name: Upload Android Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
